import {Dimensions, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  alan1: {
    flexDirection: 'row',
    gap:102,
  },
  menuIcons: {
    width: 27,
    height: 27,
    justifyContent: 'flex-start',
    tintColor: 'black',
    marginTop: 10,
    marginLeft: 8,
  },
  text1: {
    fontWeight: 'bold',
    fontSize: 27,
    color: '#5F60E0',
  },
  text2: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#D7C0FF',
    marginTop: 6,
  },
  textBar: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 9,
  },
  iconsBell: {
    width: 27,
    height: 27,
    justifyContent: 'flex-end',
    tintColor: 'black',
    marginTop: 10,
    marginRight: 8,
  },
  textGreet: {
    color: 'black',
    fontSize: 17,
    fontWeight: '400',
    marginTop: 76,
    marginLeft: 12,
  },
  textHaydi: {
    color: 'black',
    fontSize: 26,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  line: {
    padding: 2,
    width: windowWidth * 1,
    marginTop: 12,
  },
  alan2: {
    padding: 9,
    borderRadius: 16,
    backgroundColor: 'white',
    alignSelf: 'center',
    width: windowWidth * 0.7,
    marginTop: 14,
    shadowColor: '#000', // iOS için
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  backgrounnddd: {
    flex: 1,
    backgroundColor: '#F4F4F4',
  },
  searchBarContainer: {
    width: '100%',
    alignItems: 'center',
    marginTop: 18,
    marginBottom: 10,
  },
  searchBar: {
    width: '90%',
    height: 40,
    backgroundColor: '#fff',
    borderRadius: 20,
    paddingHorizontal: 18,
    fontSize: 16,
    borderWidth: 1,
    borderColor: '#E0E0E0',
    color: '#222',
  },
  postContainer: {
    width: '92%',
    alignSelf: 'center',
    backgroundColor: '#fff',
    borderRadius: 18,
    marginTop: 18,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 3,
    paddingBottom: 12,
  },
  imageArea: {
    width: '100%',
    height: 320,
    backgroundColor: '#eaeaea',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    justifyContent: 'center',
    alignItems: 'center',
  },
  iconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
    marginLeft: 16,
  },
  iconHeart: {
    width: 25,
    height: 25,
    marginRight: 18,
    tintColor: 'black',
  },
  iconComment: {
    width: 25,
    height: 25,
  },
  userRow: {
    flexDirection: 'row',
    gap: 12,
  },
  profilePic: {
    width: 40,
    height: 40,
    borderRadius: 20,
  },
  userTextContainer: {
    marginLeft: 10,
  },
  username: {
    fontWeight: 'bold',
    fontSize: 14,
    color: '#000',
    marginTop: 10,
  },
  fullname: {
    fontSize: 12,
    color: '#666',
  },
  postImage: {
    width: '100%',
    height: 450,
    resizeMode: 'cover',
    marginTop: 3,
  },
  postDescription: {
    paddingHorizontal: 15,
    paddingTop: 10,
    fontSize: 14,
    color: '#333',
  },
  daire1: {
    backgroundColor: 'white',
    width: 50,
    borderRadius: 29,
    borderWidth: 2,
    borderColor: '#6B62FF',
    height: 50,
    marginLeft: 15,
    marginTop: 7,
  },
  daireIciText: {
    fontSize: 21,
    fontWeight: 'bold',
    color: 'black',
    textAlign: 'center',
    marginTop: 10,
  },
  alan23: {
    width: windowWidth * 0.96,
    height: windowWidth * 0.4,
    backgroundColor: 'white',
    borderRadius: 12,
    shadowColor: '#000', // iOS için
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
    marginTop: 12,
    alignSelf: 'center',
    justifyContent: 'center',
  },
  testVx: {
    fontSize: 27,
    fontWeight: 'bold',
    color: '#6c63ff',
    marginTop:4,
  },
  textElite: {
    fontSize: 25,
    fontWeight: '700',
    color: '#D7C0FF',
    marginTop:5,
  },
});
