import {Dimensions, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  alan1: {
    flexDirection: 'row',
    gap:102,
  },
  menuIcons: {
    width: 27,
    height: 27,
    justifyContent: 'flex-start',
    tintColor: 'black',
    marginTop: 10,
    marginLeft: 8,
  },
  text1: {
    fontWeight: 'bold',
    fontSize: 27,
    color: '#5F60E0',
  },
  text2: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#D7C0FF',
    marginTop: 6,
  },
  textBar: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 9,
  },
  iconsBell: {
    width: 27,
    height: 27,
    justifyContent: 'flex-end',
    tintColor: 'black',
    marginTop: 10,
    marginRight: 8,
  },
  textGreet: {
    color: 'black',
    fontSize: 17,
    fontWeight: '400',
    marginTop: 76,
    marginLeft: 12,
  },
  textHaydi: {
    color: 'black',
    fontSize: 26,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  line: {
    padding: 2,
    width: windowWidth * 1,
    marginTop: 12,
  },
  alan2: {
    padding: 9,
    borderRadius: 16,
    backgroundColor: 'white',
    alignSelf: 'center',
    width: windowWidth * 0.7,
    marginTop: 14,
    shadowColor: '#000', // iOS için
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  backgrounnddd: {
    flex: 1,
    backgroundColor: '#F4F4F4',
  },
  alan2Yan: {
    flexDirection: 'row',
    gap: 13,
  },
  searchicons: {
    width: 19,
    height: 19,
    tintColor: '#418CE7',
    marginTop: 10,
    marginLeft: 6,
  },
  inputText: {
    fontSize: 14,
    fontWeight: '400',
    color: '#948D8D',
  },
  daire1: {
    width: 67,
    height: 67,
    borderRadius: 45,
    borderWidth: 2,
    borderColor: '#2498E7',
    marginLeft: 8,
  },
  daire1icon: {
    width: 62,
    height: 62,
    borderRadius: 45,
  },
  alan3Scrooll: {
    flexDirection: 'row',
    marginTop: 18,
    maxHeight: 200,
  },
  alan3ScrollTextAlani: {
    height: 87,
    backgroundColor: '#F4F4F4',
    width: 79,
    marginLeft: 21,
  },
  scrollText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'black',
    marginLeft: 12,
    marginTop: 3,
  },
  textDaire: {
    fontSize: 12,
    fontWeight: '400',
    color: 'white',
  },
  alan4: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 16,
  },
  alan4Text1: {
    color: 'black',
    fontSize: 16,
    fontWeight: 'bold',
    marginLeft: 14,
  },
  alan4Text2: {
    color: 'black',
    fontSize: 12,
    fontWeight: '400',
    marginRight: 11,
  },
  imageBack: {
    width: 178,
    height: 248,
    borderRadius: 15,
  },
  alan5Daire: {
    padding: 17,
    borderRadius: 24,
    backgroundColor: '#878488',
    width: 10,
    alignSelf: 'flex-end',
    margin: 5,
    justifyContent: 'center',
    maxHeight: 21,
  },
  hearticon: {
    width: 18,
    height: 17,
    alignSelf: 'center',
    tintColor: 'white',
  },
  text23: {
    fontSize: 19,
    fontWeight: '500',
    color: 'black',
    marginTop: 17,
  },
  text24: {
    fontSize: 13,
    fontWeight: '500',
    color: 'black',
  },
  text34: {
    fontSize: 13,
    fontWeight: '300',
    color: 'black',
    marginTop: 12,
  },
  alanimages2: {
    width: 140,
    height: 155,
    marginTop: 12,
    borderRadius: 15,
    marginLeft: 13,
  },
  images2: {
    width: windowWidth * 0.9,
    height: windowWidth * 0.4,
    borderRadius: 15,
    backgroundColor: 'white',
    alignSelf: 'center',
    marginTop: 14,
  },
  textScroll: {
    fontSize: 13,
    fontWeight: '400',
    color: 'black',
    marginLeft: 17,
  },
  imageAciklama: {
    flexDirection: 'row',
    gap: 13,
    justifyContent: 'flex-start',
    marginTop: 216,
  },
  circleicon: {
    width: 18,
    height: 18,
    marginLeft: 14,
    tintColor: 'white',
  },
  circleText: {
    fontSize: 14,
    fontWeight: '600',
    color: 'white',
  },
  searchContainerCustom: {
    backgroundColor: 'white',
    borderRadius: 16,
    alignSelf: 'center',
    width: windowWidth * 0.93,
    marginTop: 14,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.08,
    shadowRadius: 10,
    elevation: 2,
    padding: 12,
  },
  searchTypeRow: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 8,
  },
  searchTypeBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 8,
    backgroundColor: 'transparent',
  },
  selectedTypeBtn: {
    backgroundColor: 'white',
  },
  selectedTypeBtnTur: {
    backgroundColor: '#f7f7fa',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 1,
  },
  searchTypeText: {
    fontSize: 16,
    color: '#6c63ff',
    fontWeight: '500',
  },
  selectedTypeText: {
    fontWeight: 'bold',
    color: '#6c63ff',
  },
  selectedLine: {
    height: 2,
    backgroundColor: '#6c63ff',
    width: '100%',
    marginTop: 4,
    borderRadius: 2,
  },
  searchFieldsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  inputTextCustom: {
    flex: 1.5,
    fontSize: 14,
    fontWeight: '400',
    color: '#948D8D',
    backgroundColor: '#f7f7fa',
    borderRadius: 8,
    paddingHorizontal: 8,
    paddingVertical: 6,
    marginRight: 4,
  },
  dateBtn: {
    flex: 1,
    backgroundColor: '#f7f7fa',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 8,
    alignItems: 'center',
    marginRight: 4,
  },
  dateBtnText: {
    color: '#6c63ff',
    fontSize: 13,
  },
  roomBtn: {
    flex: 1.2,
    backgroundColor: '#f7f7fa',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 8,
    alignItems: 'center',
    marginRight: 4,
  },
  roomBtnText: {
    color: '#6c63ff',
    fontSize: 13,
  },
  searchBtn: {
    backgroundColor: '#6c63ff',
    borderRadius: 8,
    paddingHorizontal: 18,
    paddingVertical: 10,
    alignItems: 'center',
  },
  searchBtnText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 15,
  },
  topTabRowCustom: {
    flexDirection: 'row',
    backgroundColor: 'white',
    borderRadius: 12,
    marginTop: 18,
    marginHorizontal: 10,
    alignSelf: 'center',
    width: windowWidth * 0.9,
    justifyContent: 'space-between',
    height: windowWidth * 0.13,
  },
  topTabBtnCustom: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
    backgroundColor: 'transparent',
  },
  topTabTextCustom: {
    fontSize: 18,
    color: '#222',
    fontWeight: '500',
  },
  selectedTabTextCustom: {
    color: '#6c63ff',
    fontWeight: 'bold',
  },
  selectedTabLineCustom: {
    height: 2,
    backgroundColor: '#6c63ff',
    width: windowWidth * 0.3,
    marginTop: 6,
    borderRadius: 2,
  },
  searchAreaBoxCustom: {
    backgroundColor: 'white',
    borderRadius: 16,
    marginTop: 18,
    marginHorizontal: 10,
    padding: 18,
    gap: 16,
    alignSelf: 'center',
    width: windowWidth * 0.9,
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
  },
  inputTextCustom2: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#222',
    backgroundColor: '#f7f7fa',
    borderRadius: 10,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  rowDateCustom: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f7f7fa',
    borderRadius: 10,
    paddingHorizontal: 6,
    paddingVertical: 6,
    marginTop: 2,
  },
  dateBtn2: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 12,
  },
  dateBtnText2: {
    color: '#222',
    fontSize: 16,
    fontWeight: '500',
  },
  dateDividerCustom: {
    width: 1,
    height: 32,
    backgroundColor: '#e0e0e0',
    marginHorizontal: 4,
  },
  guestBoxCustom: {
    backgroundColor: '#f7f7fa',
    borderRadius: 10,
    padding: 12,
    marginTop: 2,
  },
  guestLabelCustom: {
    color: '#6c63ff',
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 2,
  },
  guestTextCustom: {
    color: '#222',
    fontSize: 16,
    fontWeight: '500',
  },
  searchBtnFullCustom: {
    backgroundColor: '#6c63ff',
    borderRadius: 12,
    paddingVertical: 10,
    alignItems: 'center',
    marginTop: 8,
  },
  searchBtnTextFullCustom: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 1,
  },
  guestModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.25)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  guestModalBox: {
    backgroundColor: 'white',
    borderRadius: 16,
    padding: 22,
    width: windowWidth * 0.85,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: {width: 0, height: 2},
    shadowOpacity: 0.08,
    shadowRadius: 8,
    elevation: 4,
  },
  guestRoomBox: {
    width: '100%',
    marginBottom: 18,
  },
  guestRoomTitle: {
    color: '#2563eb',
    fontWeight: 'bold',
    fontSize: 16,
    marginBottom: 8,
  },
  guestRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  guestTypeText: {
    color: '#222',
    fontSize: 16,
    fontWeight: '500',
  },
  guestCounterRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  guestCounterBtn: {
    borderWidth: 2,
    borderColor: '#60a5fa',
    borderRadius: 6,
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#f1f5f9',
  },
  guestCounterBtnText: {
    color: '#2563eb',
    fontSize: 22,
    fontWeight: 'bold',
  },
  guestCounterVal: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#2563eb',
    marginHorizontal: 8,
  },
  guestAddRoomBtn: {
    marginTop: 6,
    marginBottom: 12,
    alignSelf: 'flex-start',
  },
  guestAddRoomText: {
    color: '#2563eb',
    fontWeight: 'bold',
    fontSize: 16,
  },
  guestApplyBtn: {
    backgroundColor: '#4caf50',
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: 'center',
    width: '100%',
    marginTop: 8,
  },
  guestApplyBtnText: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 18,
    letterSpacing: 1,
  },
  rightArrowIcons:{
    width:windowWidth*0.096,
    height: windowWidth*0.08,
    marginLeft:14,
    marginTop:5,
  },
  rigthArrowText:{
    fontSize:21,
    fontWeight:'700',
    color:'black',
    marginTop:8,

  },
  rightArrowText2:{
    fontSize:14,
    fontWeight:'400',
    color:'black',
    marginHorizontal:26,
  }
});
