import {Dimensions, StyleSheet} from 'react-native';
const windowWidth = Dimensions.get('window').width;
const windowHeight = Dimensions.get('window').height;
export default StyleSheet.create({
  alan1: {
    flexDirection: 'row',
    gap:102,
  },
  menuIcons: {
    width: 27,
    height: 27,
    justifyContent: 'flex-start',
    tintColor: 'black',
    marginTop: 10,
    marginLeft: 8,
  },
  text1: {
    fontWeight: 'bold',
    fontSize: 27,
    color: '#5F60E0',
  },
  text2: {
    fontWeight: 'bold',
    fontSize: 22,
    color: '#D7C0FF',
    marginTop: 6,
  },
  textBar: {
    flexDirection: 'row',
    alignSelf: 'center',
    justifyContent: 'center',
    marginTop: 9,
  },
  iconsBell: {
    width: 27,
    height: 27,
    justifyContent: 'flex-end',
    tintColor: 'black',
    marginTop: 10,
    marginRight: 8,
  },
  textGreet: {
    color: 'black',
    fontSize: 17,
    fontWeight: '400',
    marginTop: 76,
    marginLeft: 12,
  },
  textHaydi: {
    color: 'black',
    fontSize: 26,
    fontWeight: 'bold',
    marginLeft: 12,
  },
  line: {
    padding: 2,
    width: windowWidth * 1,
    marginTop: 12,
  },
  alan2: {
    padding: 9,
    borderRadius: 16,
    backgroundColor: 'white',
    alignSelf: 'center',
    width: windowWidth * 0.7,
    marginTop: 14,
    shadowColor: '#000', // iOS için
    shadowOffset: {width: 0, height: 5},
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 5,
  },
  backgrounnddd: {
    flex: 1,
    backgroundColor: '#F4F4F4',
  },
  titleContainer: {
    backgroundColor: '#F5F5F5',
    margin: 16,
    borderRadius: 12,
    padding: 18,
    alignItems: 'center',
    shadowColor: '#000',
    shadowOpacity: 0.04,
    shadowRadius: 8,
    elevation: 2,
  },
  mainTitle: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#1a237e',
    marginBottom: 6,
    textAlign: 'center',
  },
  updateText: {
    fontSize: 14,
    color: '#888',
    marginBottom: 12,
  },
  filterRow: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  updateButton: {
    backgroundColor: '#1A237E',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
    flex: 1,
    marginRight: 8,
  },
  updateButtonText: {
    color: '#fff',
    fontWeight: '450',
    fontSize: 16,
    textAlign: 'center',
  },
  cityDropdown: {
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 18,
    flex: 1,
    marginLeft: 8,
    borderWidth: 1,
    borderColor: '#ddd',
  },
  cityDropdownText: {
    color: '#1A237E',
    fontWeight: '500',
    fontSize: 16,
    textAlign: 'center',
  },
});
